### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-appliance-iso#1]
We should add a nice logo / bootsplash at the booting of the iso.

Could be either a privacyIDEA Logo or a combination wiht netknights.
https://netknights.it/presse/logos/

**Comment by cornelinux** [comment]
We should use the logo with the dark background. It looks nicer on the dark boot splashscreen.
https://netknights.it/wp-content/uploads/2016/08/full-logo-dark-background-version-2.jpg

The following NetKnights logo should be used for the enterprise appliance:
https://netknights.it/wp-content/uploads/2018/06/NetKnights-1600px.png

**Comment by plettich** [comment]
Added Logo in e7bf68166b14918c237812eec5105d6b405ec5df
