### ISSUE TITLE
Add NetkNights pub key

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-appliance-iso#9]
We should make sure, that this is contained in the ISO
https://github.com/privacyidea/privacyidea/blob/master/deploy/privacyidea/NetKnights.pem
at /etc/privacyidea/ 
(I think it is and comes with the privacyidea-apache2 package)

But we should also add this key:

     wget https://lancelot.netknights.it/NetKnights-Release.asc

and check the fingerprint

     gpg --with-fingerprint NetKnights-Release.asc

It should look like this:

    pub  4096R/AE250082 2017-05-16 NetKnights GmbH <release@netknights.it>
      Key fingerprint = 0940 4ABB EDB3 586D EDE4  AD22 00F7 0D62 AE25 0082

     apt-key add NetKnights-Release.asc

This ensures, that the enterprise repo can be added without hassle.

**Comment by plettich** [comment]
Fixed in #10
